import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Header } from 'app/components/shared/Header'
import { Footer } from 'app/components/shared/Footer'
import { MapComponent } from './Map/MapComponent'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'GPT-4 - Leaflet - Next.js Map',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
      <body className={inter.className}><Header/>{children}</body>
      
    </html>
  )
}
